---
functional: 
- На главнорй странице пользователь может передти на страницу турнира без регистрации 
- Пользователь может зарегестрироваться на странице регистрации указав псевдоним, электронную почту, пароль и подтверждение пароля
- Пользователь может зарегестрироваться на странице регистрации если есть учетная запись на Github 
- Зарегестррованный пользователь может войти указав почу и пароль 
- Не зарегестрированный пользователь может войти на странице входа если есть учетная запись на Github 
- Пользователь может создать игру
- Пользователь может выбрать уровень сложности
- Пользователь может играть с другим пользователем
- Пользователь может играть с другом 
- Пользователь может играть с ботом
- Пользователь может установить время для выполнения задания в игре
- Пользовател можетвыбрать задачу из списка
- Пользовател можетвыбрать задачу введя название
- Пользователь может фильтровать задания по тегу
- На странице турнира пользовател может посмотреть руководство по странице турнира
- На странице турнира пользовател может выбрать язык описания задачи 
- На странице турнира пользовател может выбрать язык программирования для решения задачи 
- На странице турнира пользовател может сдаться нажав кнопку 
- На странице турнира пользовател может сбросить код в редакторе нажав кнопку 
- На странице турнира пользовател может запуститьт код нажав кнопку 
- На странице турнира пользовател может просмотреть результат работы кода 
- На странице турнира пользовател может просмотреть результат работы кода соперника
- На странице турнира пользовател может выбрать стиль текстового редактора Vim 
- На странице турнира пользовател может выбрать стиль текстового редактора обычный
- На странице турнира пользовател может выбрать цвет фона текстового редактора светлый или темный
- На странице турнира пользовател может писать в чате сопернику 
- На странице турнира пользовател может запросить матч-реванш
- На странице турнира пользовател может просмотреть историю турнира 
- На странице турнира пользовател может оставить сообщение обратной сваязи 
- На странице турнира пользовател может выйти из турнира
non-functional:
- Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен быть удобным на мобильном устройстве
- Сайт должен быть протестирован на совместимость с последними версиями браузеров
- Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
- Название кнопки "Send Feedback"('оставить отзыв') на странице турнира заменить на "Feedback"('обратная связь') 
